version: 2

models:
  - name: stg_orders
    description: Cleaned order data

    columns:
      - name: order_id
        description: Primary key

        data_tests:
          - unique
          - not_null

      - name: customer_id

        data_tests:
          - not_null

      - name: order_status

        data_tests:
          - accepted_values:
              arguments:
                values:
                  - placed
                  - shipped
                  - completed
                  - return_pending
                  - returned

  - name: stg_interviews
    description: Cleaned interview data

  - name: stg_interviews_latest
    description: Latest interview record per interview

  - name: dim_candidate
    description: Candidate dimension table

  - name: dim_interviewer
    description: Interviewer dimension table

  - name: fct_interview
    description: Interview fact table
